image:
  name: maven:3.8.3-openjdk-21

definitions:
  caches:
    sonar: ~/.sonar

steps:

  - step: &tests
      name: Maven Tests
      caches:
        - maven
      script:
        - mvn test

  - step: &package
      name: Maven Package
      image: opennms/build-env:21.0.3.0.7-3.8.7-b9875
      caches:
        - maven
      script:
        - mvn -B -Pprod -DprofileIdEnabled=true -Dmaven.test.skip=true clean package
      artifacts:
        - api/target/**.jar
        - api/newrelic/**

  - step: &build-docker
      deployment: production
      name: Build Docker Images
      services:
        - docker
      script:
        - docker build --build-arg NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY --build-arg SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE -t api -f api/Dockerfile .
        - pipe: atlassian/aws-ecr-push-image:1.6.2
          variables:
            IMAGE_NAME: backend-api
            TAGS: '${BITBUCKET_TAG} latest'
        - pipe: atlassian/aws-ecs-deploy:1.6.2
          variables:
            CLUSTER_NAME: backend-api
            SERVICE_NAME: api
            TASK_DEFINITION: tasks/task-api.json
pipelines:
  branches:
    master:
      - parallel:
          - step: *tests
          - step: *package
      - step: *build-docker