name: Hello World CI

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"

      - name: Inspect Environment
        run: |
          echo "Running on:"
          uname -a
          lsb_release -a
          echo "Node.js version:"
          node -v
          echo "Python version:"
          python --version
          echo "Docker version:"
          docker --version
